// Mocks generated by Mockito 5.4.4 from annotations
// in my_cactus/test/widget/screens/welcome_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:ui' as _i7;

import 'package:flutter/foundation.dart' as _i2;
import 'package:flutter/material.dart' as _i9;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;
import 'package:my_cactus/models/plant.dart' as _i5;
import 'package:my_cactus/presentation/providers/cloud_storage_provider.dart'
    as _i8;
import 'package:my_cactus/presentation/providers/plant_crud_provider.dart'
    as _i10;
import 'package:my_cactus/presentation/providers/weather_provider.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeValueNotifier_0<T> extends _i1.SmartFake
    implements _i2.ValueNotifier<T> {
  _FakeValueNotifier_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [WeatherProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockWeatherProvider extends _i1.Mock implements _i3.WeatherProvider {
  MockWeatherProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isLoading => (super.noSuchMethod(
        Invocation.getter(#isLoading),
        returnValue: false,
      ) as bool);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  _i4.Future<void> initLocation() => (super.noSuchMethod(
        Invocation.method(
          #initLocation,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<String?> getCity() => (super.noSuchMethod(
        Invocation.method(
          #getCity,
          [],
        ),
        returnValue: _i4.Future<String?>.value(),
      ) as _i4.Future<String?>);

  @override
  _i4.Future<void> setCity(String? city) => (super.noSuchMethod(
        Invocation.method(
          #setCity,
          [city],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<String> getWeatherAdvice(_i5.Plant? plant) => (super.noSuchMethod(
        Invocation.method(
          #getWeatherAdvice,
          [plant],
        ),
        returnValue: _i4.Future<String>.value(_i6.dummyValue<String>(
          this,
          Invocation.method(
            #getWeatherAdvice,
            [plant],
          ),
        )),
      ) as _i4.Future<String>);

  @override
  void addListener(_i7.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i7.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [CloudStorageProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockCloudStorageProvider extends _i1.Mock
    implements _i8.CloudStorageProvider {
  MockCloudStorageProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isConnected => (super.noSuchMethod(
        Invocation.getter(#isConnected),
        returnValue: false,
      ) as bool);

  @override
  bool get isSyncing => (super.noSuchMethod(
        Invocation.getter(#isSyncing),
        returnValue: false,
      ) as bool);

  @override
  _i2.ValueNotifier<double> get syncProgress => (super.noSuchMethod(
        Invocation.getter(#syncProgress),
        returnValue: _FakeValueNotifier_0<double>(
          this,
          Invocation.getter(#syncProgress),
        ),
      ) as _i2.ValueNotifier<double>);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  void cancelSync() => super.noSuchMethod(
        Invocation.method(
          #cancelSync,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i4.Future<void> handleDeepLink(Uri? uri) => (super.noSuchMethod(
        Invocation.method(
          #handleDeepLink,
          [uri],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> connectToYandexDisk(_i9.BuildContext? context) =>
      (super.noSuchMethod(
        Invocation.method(
          #connectToYandexDisk,
          [context],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> connectToYandexDiskSilently() => (super.noSuchMethod(
        Invocation.method(
          #connectToYandexDiskSilently,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> disconnect() => (super.noSuchMethod(
        Invocation.method(
          #disconnect,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> syncData(_i10.PlantCrudProvider? plantCrudProvider) =>
      (super.noSuchMethod(
        Invocation.method(
          #syncData,
          [plantCrudProvider],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> loadFromCloud(_i9.BuildContext? context) =>
      (super.noSuchMethod(
        Invocation.method(
          #loadFromCloud,
          [context],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<String> uploadPhotoToYandexDisk(String? filePath) =>
      (super.noSuchMethod(
        Invocation.method(
          #uploadPhotoToYandexDisk,
          [filePath],
        ),
        returnValue: _i4.Future<String>.value(_i6.dummyValue<String>(
          this,
          Invocation.method(
            #uploadPhotoToYandexDisk,
            [filePath],
          ),
        )),
      ) as _i4.Future<String>);

  @override
  _i4.Future<List<String>> getCloudPhotos() => (super.noSuchMethod(
        Invocation.method(
          #getCloudPhotos,
          [],
        ),
        returnValue: _i4.Future<List<String>>.value(<String>[]),
      ) as _i4.Future<List<String>>);

  @override
  _i4.Future<void> deletePhotoFromYandexDisk(String? fileUrl) =>
      (super.noSuchMethod(
        Invocation.method(
          #deletePhotoFromYandexDisk,
          [fileUrl],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> loadCredentials() => (super.noSuchMethod(
        Invocation.method(
          #loadCredentials,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> fetchLastCloudUpdate() => (super.noSuchMethod(
        Invocation.method(
          #fetchLastCloudUpdate,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> loadDataFromCloud(
          _i10.PlantCrudProvider? plantCrudProvider) =>
      (super.noSuchMethod(
        Invocation.method(
          #loadDataFromCloud,
          [plantCrudProvider],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> syncUserPhotos(_i10.PlantCrudProvider? plantCrudProvider) =>
      (super.noSuchMethod(
        Invocation.method(
          #syncUserPhotos,
          [plantCrudProvider],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  void invalidateAllCaches(_i10.PlantCrudProvider? plantCrudProvider) =>
      super.noSuchMethod(
        Invocation.method(
          #invalidateAllCaches,
          [plantCrudProvider],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addListener(_i7.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i7.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
