// Mocks generated by Mockito 5.4.4 from annotations
// in my_cactus/test/unit/repositories/plant_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:my_cactus/data/datasources/local/plant_local_datasource.dart'
    as _i2;
import 'package:my_cactus/data/models/plant_dto.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [PlantLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockPlantLocalDataSource extends _i1.Mock
    implements _i2.PlantLocalDataSource {
  MockPlantLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.PlantDto>> getAllPlants() => (super.noSuchMethod(
        Invocation.method(
          #getAllPlants,
          [],
        ),
        returnValue: _i3.Future<List<_i4.PlantDto>>.value(<_i4.PlantDto>[]),
      ) as _i3.Future<List<_i4.PlantDto>>);

  @override
  _i3.Future<_i4.PlantDto?> getPlantById(String? id) => (super.noSuchMethod(
        Invocation.method(
          #getPlantById,
          [id],
        ),
        returnValue: _i3.Future<_i4.PlantDto?>.value(),
      ) as _i3.Future<_i4.PlantDto?>);

  @override
  _i3.Future<void> addPlant(_i4.PlantDto? plant) => (super.noSuchMethod(
        Invocation.method(
          #addPlant,
          [plant],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> updatePlant(_i4.PlantDto? plant) => (super.noSuchMethod(
        Invocation.method(
          #updatePlant,
          [plant],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> deletePlant(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deletePlant,
          [id],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<List<_i4.PlantDto>> getPlantsByStatus(String? status) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPlantsByStatus,
          [status],
        ),
        returnValue: _i3.Future<List<_i4.PlantDto>>.value(<_i4.PlantDto>[]),
      ) as _i3.Future<List<_i4.PlantDto>>);

  @override
  _i3.Future<List<_i4.PlantDto>> getPlantsByCategory(String? category) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPlantsByCategory,
          [category],
        ),
        returnValue: _i3.Future<List<_i4.PlantDto>>.value(<_i4.PlantDto>[]),
      ) as _i3.Future<List<_i4.PlantDto>>);

  @override
  _i3.Future<List<_i4.PlantDto>> searchPlants(String? query) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchPlants,
          [query],
        ),
        returnValue: _i3.Future<List<_i4.PlantDto>>.value(<_i4.PlantDto>[]),
      ) as _i3.Future<List<_i4.PlantDto>>);

  @override
  _i3.Future<void> clearAll() => (super.noSuchMethod(
        Invocation.method(
          #clearAll,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> rebuildIndex() => (super.noSuchMethod(
        Invocation.method(
          #rebuildIndex,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}
